name: Link GHA Actions
author: Taylor Perkins
description: Given another repo containing your reusable actions, link them to the current repo with a prefix
inputs:
  repository:
    description: actions/checkout@v2::repository
    required: true

  token:
    description: actions/checkout@v2::token
    required: false
    default: ''

  ref:
    description: actions/checkout@v2::ref
    default: 'main'
    required: false

  prefix:
    description: Prefix to use for workflows and actions
    default: ''
    required: false

runs:
  using: composite
  steps:
    - name: Clone repo
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        ref: ${{ inputs.ref }}

    - run: mv ${GITHUB_WORKSPACE}/.temp ${{ runner.temp }}/gha
      shell: bash

    - working-directory: ${{ runner.temp }}/gha
      id: link
      shell: bash
      run: |
        ls -al .github/actions
        if [[ -d .github/actions ]]
        then
          mkdir -p ${GITHUB_WORKSPACE}/.github/actions
          for name in `ls .github/actions`
          do
            echo "Linking ${name} to ${GITHUB_WORKSPACE}/.github/actions/${{ inputs.prefix }}${name}"
            ln -s "${{ runner.temp }}/gha/.github/actions/${name}" "${GITHUB_WORKSPACE}/.github/actions/${{ inputs.prefix }}${name}"
          done
        fi
