name: Link GHA Actions
author: Taylor Perkins
description: Given another repo containing your reusable actions, link them to the current repo with a prefix
inputs:
  repository:
    description: actions/checkout@v2::repository
    required: true

  token:
    description: actions/checkout@v2::token
    required: false
    default: ''

  ref:
    description: actions/checkout@v2::ref
    default: 'main'
    required: false

  prefix:
    description: Prefix to use for workflows and actions
    default: ''
    required: false

runs:
  using: composite
  steps:
    - name: Clone repo
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        ref: ${{ inputs.ref }}
        path: .link-actions
        set-safe-directory: false

    - run: mv ${GITHUB_WORKSPACE}/.link-actions ${{ runner.temp }}/.link-actions
      shell: bash

    - working-directory: ${{ runner.temp }}/.link-actions
      id: link
      shell: bash
      run: |
        ls -al .github/actions
        if [[ -d .github/actions ]]
        then
          for p in `find .github/actions -name action.yml`
          do
            d=$(dirname $p)
            mkdir -p "${GITHUB_WORKSPACE}/${d}"
            ln -s "`pwd`/${d}/" "${GITHUB_WORKSPACE}/${d}"
          done
          # normal
          find "${GITHUB_WORKSPACE}/.github/actions" -name action.yml
          # links
          find "${GITHUB_WORKSPACE}/.github/actions" -type l -ls
        fi
